name: Cargo build

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: eqr - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
    - uses: actions/checkout@v4
    - run: |
        rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
        rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: |
        env RUSTFLAGS='-C target-feature=+crt-static'
        cargo build --release --verbose --target=x86_64-unknown-linux-musl
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: eqr
        path: |
          /home/runner/work/eqr/eqr/target/x86_64-unknown-linux-musl/release/qr
          /home/runner/work/eqr/eqr/target/x86_64-unknown-linux-musl/release/promptpay
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: cargo fmt --check
        run: |
          if ! rustfmt --check --edition 2024 $(git ls-files '*.rs')
          then
            printf "Please run \`rustfmt --edition 2024 \$(git ls-files '*.rs')\` to fix rustfmt errors.\nSee docs/CODE_STYLE.md for more details.\n" >&2
            exit 1
          fi
