name: Cargo build

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: eqr - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
    - uses: actions/checkout@v4
    - run: |
        rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
        rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: |
        env RUSTFLAGS='-C target-feature=+crt-static'
        cargo build --release --verbose --target=x86_64-unknown-linux-musl
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: eqr
        path: |
          /home/runner/work/eqr/eqr/target/x86_64-unknown-linux-musl/release/qr
          /home/runner/work/eqr/eqr/target/x86_64-unknown-linux-musl/release/promptpay
