name: Cargo build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: qr - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          #- beta
          #- nightly

    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --release --verbose
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: qr
        path: /home/runner/work/qr/qr/target/release/qr
